id: P75505E85
initial_creation_type: input
source_metadata:
  title: Bodhicitta Series
  language: es
  description: Texts on the subject of bodhicitta (byang chub sems), which (on the
    relative level, at least) is the compassionate wish to attain enlightenment for
    the sake of all living beings—and has been variously translated into English as
    'thought of enlightenment', 'awakening-mind', 'spirit of awakening', etc.
  volume:
    567797727a1b469b8b9589191a5f058f:
      title: Advice for Tenzin Jamchen
      parent: Advice
    59261f75697347dc856ea30e81f2edd2:
      title: Bodhicitta Aspiration
      parent: Aspirations
    d357059bbc5d439bafb28769e7936eca:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspirations
    747f6fd7fc61455ca7e6cbe5f581285d:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Commentaries
    ee685082cf5340d6ac6824336a20667b:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    71adbaf0551b42239e6fb56468b50b68:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
    87a686edd8fd40e0bbc30c1352ac5e6e:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    7400f03fce9145099b9a8351ea6be0ec:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    49eeef15c9eb41ebaf4e55ac376a0a47:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Practices
    f0829c62c08e450d9c275f8638c8c34d:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    63c664c19be0482c93159cf15660e144:
      title: The Three Noble Principles
      parent: Three Noble Principles
created_at: '2022-03-01T03:03:50.798968'
last_modified_at: '2022-03-01T03:03:50.798971'
